export const SYSTEM_USER_ID = 'SYSTEM';

export enum TipoMovimiento {
  ENTRADA_BODEGA = 'ENTRADA_BODEGA',
  ENTRADA_TRANSFERENCIA = 'ENTRADA_TRANSFERENCIA',
  ENTRADA_DEVOLUCION = 'ENTRADA_DEVOLUCION',
  ENTRADA_REVERSION = 'ENTRADA_REVERSION',
  TRANSFERENCIA_BODEGA_VENTAS = 'TRANSFERENCIA_BODEGA_VENTAS',
  TRANSFERENCIA_VENTAS_BODEGA = 'TRANSFERENCIA_VENTAS_BODEGA',
  TRANSFERENCIA_BODEGA_MERMAS = 'TRANSFERENCIA_BODEGA_MERMAS',
  TRANSFERENCIA_VENTAS_MERMAS = 'TRANSFERENCIA_VENTAS_MERMAS',
  TRANSFERENCIA_VENTAS_CADUCADOS = 'TRANSFERENCIA_VENTAS_CADUCADOS',
  TRANSFERENCIA_VENTAS_DONACION = 'TRANSFERENCIA_VENTAS_DONACION',
  TRANSFERENCIA_VENTAS_DESTRUCCION = 'TRANSFERENCIA_VENTAS_DESTRUCCION',
  TRANSFERENCIA_ENTRE_LOTES = 'TRANSFERENCIA_ENTRE_LOTES',
  TRANSFERENCIA_OTRO = 'TRANSFERENCIA_OTRO',
  VENTA = 'VENTA',
  SALIDA_MERMA = 'SALIDA_MERMA',
  SALIDA_CADUCADO = 'SALIDA_CADUCADO',
  SALIDA_DONACION = 'SALIDA_DONACION',
  SALIDA_DESTRUCCION = 'SALIDA_DESTRUCCION',
  AJUSTE_ENTRADA = 'AJUSTE_ENTRADA',
  AJUSTE_SALIDA = 'AJUSTE_SALIDA',
  ENTRADA_INICIAL = 'ENTRADA_INICIAL',
}

export enum TipoReversion {
  FAILED_BATCH = 'FAILED_BATCH',
  MANUAL_REVERSION = 'MANUAL_REVERSION',
  ROLLBACK = 'ROLLBACK',
  CANCELACION = 'CANCELACION',
}

export enum OrigenOperacion {
  POS = 'POS',
  WEB = 'WEB',
  API = 'API',
  ADMIN = 'ADMIN',
  SYSTEM = 'SYSTEM',
}
