export enum FormaPago {
  EFECTIVO = '01',
  CHEQUE = '02',
  TRANSFERENCIA = '03',
  TARJETA_CREDITO = '04',
  MONEDERO_ELECTRONICO = '05',
  DINERO_ELECTRONICO = '06',
  VALES_DESPENSA = '08',
  DACION_PAGO = '12',
  PAGO_SUBROGADO = '13',
  PAGO_CONSIGNACION = '14',
  CONDONACION = '15',
  COMPENSACION = '17',
  NOVACION = '18',
  CONFUSION = '19',
  REMISION_DE_DEUDA = '20',
  PRESCRIPCION_O_CADUCIDAD = '21',
  A_SATISFACCION_DEL_ACREEDOR = '23',
  POR_CUENTA_DE_TERCERO = '24',
  PAGO_DIFERIDO = '25',
  PAGO_EN_PARCIALIDADES = '26',
  COBRO_EN_ESPEcie = '27',
  BILLETE_DE_DESPENSA = '28',
  TARJETA_DE_DEBITO = '29',
  TARJETA_DE_SERVICIO = '30',
  APLICACION_DE_ANTICIPOS = '31',
  POR_IDENTIFICAR = '99',
}

export const FormaPagoNombres: Record<FormaPago, string> = {
  [FormaPago.EFECTIVO]: '01 - Efectivo',
  [FormaPago.CHEQUE]: '02 - Cheque nominativo',
  [FormaPago.TRANSFERENCIA]: '03 - Transferencia electrónica de fondos',
  [FormaPago.TARJETA_CREDITO]: '04 - Tarjeta de crédito',
  [FormaPago.MONEDERO_ELECTRONICO]: '05 - Monedero electrónico',
  [FormaPago.DINERO_ELECTRONICO]: '06 - Dinero electrónico',
  [FormaPago.VALES_DESPENSA]: '08 - Vales de despensa',
  [FormaPago.DACION_PAGO]: '12 - Dación en pago',
  [FormaPago.PAGO_SUBROGADO]: '13 - Pago por subrogación',
  [FormaPago.PAGO_CONSIGNACION]: '14 - Pago por consignación',
  [FormaPago.CONDONACION]: '15 - Condonación',
  [FormaPago.COMPENSACION]: '17 - Compensación',
  [FormaPago.NOVACION]: '18 - Novación',
  [FormaPago.CONFUSION]: '19 - Confusión',
  [FormaPago.REMISION_DE_DEUDA]: '20 - Remisión de deuda',
  [FormaPago.PRESCRIPCION_O_CADUCIDAD]: '21 - Prescripción o caducidad',
  [FormaPago.A_SATISFACCION_DEL_ACREEDOR]: '23 - A satisfacción del acreedor',
  [FormaPago.POR_CUENTA_DE_TERCERO]: '24 - Por cuenta de tercero',
  [FormaPago.PAGO_DIFERIDO]: '25 - Pago diferido',
  [FormaPago.PAGO_EN_PARCIALIDADES]: '26 - Pago en parcialidades',
  [FormaPago.COBRO_EN_ESPEcie]: '27 - Cobro en especie',
  [FormaPago.BILLETE_DE_DESPENSA]: '28 - Billete de despensa',
  [FormaPago.TARJETA_DE_DEBITO]: '29 - Tarjeta de débito',
  [FormaPago.TARJETA_DE_SERVICIO]: '30 - Tarjeta de servicio',
  [FormaPago.APLICACION_DE_ANTICIPOS]: '31 - Aplicación de anticipos',
  [FormaPago.POR_IDENTIFICAR]: '99 - Por identificar',
};
