export enum RegimenFiscal {
  GENERAL = '601',
  PERSONA_MORAL = '603',
  SUELDOS = '605',
  ARRENDAMIENTO = '606',
  INCORPORACION_FISCAL = '608',
  COMPENSACIONES = '609',
  OPCION_VOLUNTARIA = '610',
  OPCION_CUMPLIMIENTO = '611',
  SINDICATOS = '612',
  NO_OBSTANTE_RETENCION = '614',
  HONORARIOS = '615',
  DRAMATURGIA = '616',
  ARTISTAS = '617',
  FIDEICOMISOS = '618',
  RECURSOS_NAVCONT = '620',
  SECTOR_PRIMARIO = '621',
  ACTIVIDADES_AGRICOLAS = '622',
  SILVICULTURA = '623',
  PESCA = '624',
  COMBUSTIBLES = '625',
  MINERO = '626',
  SEMARNAT = '627',
  IESPS = '628',
  OPERACIONES_FINANCIERAS = '629',
  SERVICIOS_PARCIALIDAD_FACTURAJA = '630',
  SECTOR_HIDROCARBUROS = '631',
  ASIMILABLES = '633',
  SOCIEDADES_COOPERATIVAS = '634',
  ACTIVIDADES_ECONOMICAS = '635',
  SECTOR_PRIMARIO_2022 = '636',
  REGIMEN_SIMPLIFICADO = '637',
  GRUPO_SOCIEDADES = '638',
  COORDINADOS = '639',
  PROVEEDORES_TURISTICOS = '640',
  SERVICIOS_PREVISIONALES = '641',
  REGIMEN_FISCAL_PREFERENTE = '642',
  INCORPORACION_TECNOLOGICA = '643',
  OPCIONES_FISCALES_TURISMO = '644',
  DIVIDENDOS = '645',
  PERSONAS_MORALES_CONSORCIO = '646',
  ARRENDAMIENTO_NVO_REGIMEN = '647',
  EFECTOS_FISCALES = '648',
  PAGOS_OTORGADOS = '649',
  OPERACIONES_GRAVABLES_IMPUESTO_CAJAS = '650',
}

export const RegimenFiscalNombres: Record<string, string> = {
  [RegimenFiscal.GENERAL]: '601 - General de Ley Personas Morales',
  [RegimenFiscal.PERSONA_MORAL]: '603 - Personas Morales con ingresos acumulables',
  [RegimenFiscal.SUELDOS]: '605 - Sueldos y salarios',
  [RegimenFiscal.ARRENDAMIENTO]: '606 - Arrendamiento',
  [RegimenFiscal.INCORPORACION_FISCAL]: '608 - Incorporación fiscal',
  [RegimenFiscal.COMPENSACIONES]: '609 - Compensaciones',
  [RegimenFiscal.OPCION_VOLUNTARIA]: '610 - Opción de pago sin flujos de efectivo',
  [RegimenFiscal.OPCION_CUMPLIMIENTO]: '611 - Opción de cumplimiento',
  [RegimenFiscal.SINDICATOS]: '612 - Sindicatos',
  [RegimenFiscal.NO_OBSTANTE_RETENCION]: '614 - No obstante retención',
  [RegimenFiscal.HONORARIOS]: '615 - Honorarios médicos y dentales',
  [RegimenFiscal.DRAMATURGIA]: '616 - Dramatururgia',
  [RegimenFiscal.ARTISTAS]: '617 - Artistas y deportistas',
  [RegimenFiscal.FIDEICOMISOS]: '618 - Fideicomisos',
  [RegimenFiscal.RECURSOS_NAVCONT]: '620 - Recursos navcontrolled',
  [RegimenFiscal.SECTOR_PRIMARIO]: '621 - Sector primario',
  [RegimenFiscal.ACTIVIDADES_AGRICOLAS]: '622 - Actividades agrícolas',
  [RegimenFiscal.SILVICULTURA]: '623 - Silvicultura',
  [RegimenFiscal.PESCA]: '624 - Pesca',
  [RegimenFiscal.COMBUSTIBLES]: '625 - Combustibles',
  [RegimenFiscal.MINERO]: '626 - Minero',
  [RegimenFiscal.SEMARNAT]: '627 - SEMARNAT',
  [RegimenFiscal.IESPS]: '628 - IEPS',
  [RegimenFiscal.OPERACIONES_FINANCIERAS]: '629 - Operaciones Financieras',
  [RegimenFiscal.SERVICIOS_PARCIALIDAD_FACTURAJA]: '630 - Servicios parcialidad',
  [RegimenFiscal.SECTOR_HIDROCARBUROS]: '631 - Sector hidrocarburos',
  [RegimenFiscal.ASIMILABLES]: '633 - Asimilables a salarios',
  [RegimenFiscal.SOCIEDADES_COOPERATIVAS]: '634 - Sociedades Cooperativas',
  [RegimenFiscal.ACTIVIDADES_ECONOMICAS]: '635 - Actividades económicas',
  [RegimenFiscal.SECTOR_PRIMARIO_2022]: '636 - Sector primario 2022',
  [RegimenFiscal.REGIMEN_SIMPLIFICADO]: '637 - Régimen Simplificado Confianza',
  [RegimenFiscal.GRUPO_SOCIEDADES]: '638 - Grupo de sociedades',
  [RegimenFiscal.COORDINADOS]: '639 - Coordinados',
  [RegimenFiscal.PROVEEDORES_TURISTICOS]: '640 - Proveedores turísticos',
  [RegimenFiscal.SERVICIOS_PREVISIONALES]: '641 - Servicios predefinitive',
  [RegimenFiscal.REGIMEN_FISCAL_PREFERENTE]: '642 - Regimen fiscal preferente',
  [RegimenFiscal.INCORPORACION_TECNOLOGICA]: '643 - Incorporación tecnológica',
  [RegimenFiscal.OPCIONES_FISCALES_TURISMO]: '644 - Opciones fiscales turismo',
  [RegimenFiscal.DIVIDENDOS]: '645 - Dividendos',
  [RegimenFiscal.PERSONAS_MORALES_CONSORCIO]: '646 - Personas morales en consorcio',
  [RegimenFiscal.ARRENDAMIENTO_NVO_REGIMEN]: '647 - Arrendamiento nuevo régimen',
  [RegimenFiscal.EFECTOS_FISCALES]: '648 - Efectos fiscales',
  [RegimenFiscal.PAGOS_OTORGADOS]: '649 - Pagos otorgados',
  [RegimenFiscal.OPERACIONES_GRAVABLES_IMPUESTO_CAJAS]: '650 - Operaciones grabables cajas',
};